name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['1.12', '1']
        include:
            - os: ubuntu-latest
              version: nightly  

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}

      # Install Julia dependencies 
      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

      # Force PyCall to use Conda before testing
      - name: Force PyCall to use Julia Conda
        run: |
            julia --project=. -e 'ENV["PYTHON"] = ""; using Pkg; Pkg.build("PyCall")'

      # Install SymPy inside Conda
      - name: Install SymPy
        run: |
            julia --project=. -e 'using PyCall; pyimport_conda("sympy", "sympy")'

      # Run tests
      - name: Run tests
        run: julia --project=. -e 'using Pkg; Pkg.test(coverage=true)'